name: Build & Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
      - name: Install yarn
        run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - name: Install VueCLI
        run: |
          yarn global add @vue/cli
          export PATH="$(yarn global bin):$PATH"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install yarn dependencies
        run: |
          yarn install
          yarn run build
      - name: Lint JS
        run: yarn run lint
      # # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      # - name: Hello world
      #   uses: actions/hello-world-javascript-action@v1
      #   with:
      #     who-to-greet: 'Mona the Octocat'
      #   id: hello
      # # This step prints an output (time) from the previous step's action.
      # - name: Echo the greeting's time
      #   run: echo 'The time was ${{ steps.hello.outputs.time }}.'
